### ISSUE TITLE
Allow simple transfer of images between objects

### ISSUE THREAD

**Issue by grololo06** [oceanomics/ecotaxa_dev#425]
Use case: A user realizes after an import that a second image refers to the same animal, or that 2 images in an object are not related.

In the manual classification page, we would go for a keyboard shortcut, e.g. CTRL-G (for "grouping").
If 2 objects are selected, each one having an image, and are compatible, you hit "CTRL-G" on the keyboard, the 2 objects would become one, with 2 images in it.
If a single object is selected and has 2 images, you hit "CTRL-G" and end up with a new object, the old one losing an image in favor of the new one.

Eventually, it would be less user friendly, e.g. you would have to use dedicated buttons in the object details page (eye icon).

During grouping, one of the objects would be erased, implying a data loss.

**Comment by jiho** [comment]
As discussed, I don't see the use case here.

The only case when two images of the same animal are taken that I know about is for continuously sampling instruments with a high frame rate; e.g. the instrument takes an image of 1L of water every second, the animal does not have time to move out and is imaged several times (let us say 2).

If we keep the two images separate and compute a concentration we get `2 objects / 2 L` = `1 animal / L` which is correct.

If we merge the two, we count `1 object / 2 L` = `0.5 animal / L` which is incorrect.

Furthermore, the features of the two images are likely to be different if they are two slightly different images from the same animal. Which to keep?

Finally, relying on human detection of such duplicated animals is unreliable because the big, slow moving ones will be detected but not the smaller or faster ones.

**Comment by jiho** [comment]
I assume that:
- you have an instrument that takes frames at regular intervals (a VPR I think, right?)
- each frame represents a know volume (let us say 1L for the sake of simplicity)
- you extract objects from each frame in an automated way; there can be several objects on a frame, or none at all
- you identify each object in EcoTaxa
- from the identifications, you can to compute in situ concentrations over some sort of bin (every 1m in depth, every 10 in of recording, whatever)

If that is indeed the case, then you are in a situation we know well, which is similar to the UVP.

What may happen is that the instrument sits in a single place, or moves up and down because of waves, and takes several frames of the same water parcel, and therefore the same organisms. In EcoTaxa, you then have several images of the same copepod, e.g.
	https://ecotaxa.obs-vlfr.fr/objectdetails/168472940?w=1227&h=869
	https://ecotaxa.obs-vlfr.fr/objectdetails/168472939?w=1227&h=869
	https://ecotaxa.obs-vlfr.fr/objectdetails/168472938?w=1227&h=869
	https://ecotaxa.obs-vlfr.fr/objectdetails/168472937?w=1227&h=869
	https://ecotaxa.obs-vlfr.fr/objectdetails/168472936?w=1227&h=869
	https://ecotaxa.obs-vlfr.fr/objectdetails/168472935?w=1227&h=869
	https://ecotaxa.obs-vlfr.fr/objectdetails/168472934?w=1227&h=869
You would like to avoid the tedious work of labelling each of them separately so you would want to regroup them (or, alternatively, you could label one as Copepod and the others as "duplicate" and never look at them again, this is what we did with the UVP). In either case, instead of having 7 EcoTaxa records in the "Copepod" category, you get just 1.

The problem arises when you compute concentrations afterwards. Your depth/time bin contains n frames, here 7 at least, so there were 7L of water imaged and you compute your concentration as 1 Copepod / 7 L = 0.14 #/L. But in fact you images 7 times the *same* L of water, so the real in situ concentration is 1 Copepod / 1 L = 1 #/L. If, instead of regrouping the images, you kept them separate, you would have 7 Copepod / 7L = 1 #/L therefore the correct concentration.

So you can:

1. either keep your pre-processing systematic: process all frames, output all segmented images, upload everything to EcoTaxa, identify everything and then compute concentrations as
	number in EcoTaxa / (nb of frames taken * volume of a frame)
This will result in correct concentrations but with an uneven sampling effort (more effort where the instrument stayed still and took many frames of the same water parcel => bias in the computation of average concentrations in the station towards the concentration in that particular place)

2. detect the cases of frames taken in the same location during preprocessing (by looking at depth or other information on the position of the instrument), skip those frames for the extraction of objects, remove them from the computation of volume sampled (i.e. make as if they never existed), then upload to EcoTaxa and compute concentrations as
	number in EcoTaxa / (nb of non-repeated frames, on which objects were extracted * volume of a frame)
This will also result in correct concentrations and remove the sampling bias.

Trying to remove duplicated frames by detecting duplicated objects after the fact is necessarily flawed because it depends on a human's ability to detect that two objects are the same. This is "easy" for Copepods that are funky looking or with a piece of junk on their antenna, this is much harder for featureless pieces of marine snow for example.
In the case above, let us assume there was a piece of marine snow on the same frame as the Copepod. You (just like anyone) can't tell a piece of marine snow from another, so you do not detect it as a duplicate and do not regroup it under a single object. You would compute the concentration of the regrouped Copepod as 1 / 7 = 0.14 #/L but the concentration of marine snow as 7 / 7 = 1 #/L and conclude that there is 7 times more marine snow than Copepod, which is of course incorrect.

The only ~correct solution would be to:
- detect that two objects are the same
- ask to regroup them
- then EcoTaxa would regroup *all* couples of objects from the two frames using the frame identifiers and some sort of heuristic about their position on the frame
- classify taxonomically the regrouped objects as single entities
- compute concentrations by counting the regrouped frames as a single frame to compute the sampled volume
But this is impossible currently because we do not have frame identifiers and we do not necessarily have position on the frame. Even if we had, it would be quite complicated and specific within the grand scheme of EcoTaxa. And finally it would still be incorrect if the two frames are not exactly overlapping in terms of volume sampled.

So our solution for the UVP is to not care about it, identify everything, accept some sampling effort bias in the data and compensate for it by computing concentrations per small depth bins and then compute average concentrations over larger bins not weighted by the volume sampled in each bin. Example:
	from 10 to 15 m, 50 UVP frames, concentration 0.1 #/L
	from 15 to 20 m, 200 UVP frames (the UVP stayed still for a big), concentration 0.15 #/L
	from 10 to 25 m, 50 UVP frames (descent restarted normally), concentration 0.1 #/L
If we compute the concentration from 10 to 25 m by summing all objects classified between those depths and dividing by the volume corresponding to 50+200+50 frames we get a result strongly biased towards 0.15 (it would be 0.13 #/L).
If we compute the concentrations per 5 m bin and then compute the average concentration from 10 to 25 m simply as (0.1 + 0.15 + 0.1) / 3 = 0.11 #/L we get something that is much less biased.

**Comment by picheral** [comment]
The question of the minimum concentration of a given object that the instrument can count is also important in the LPM spectra. The bigger the volume (by summing depth classes, increasing image volume or frequency...), the lower or the more accurate concentrations will be observed.
It makes thus no sense for me to remove duplicated copepods (as an example) if you do not remove the images of the same volume of water which is impossible in many cases. My opinion is that we should keep all successive images of the same object as we do with LPM data just because we use all the images to compute the sampled volume.
I thus use the DUPLICATE category to sort the parts of large bodies such as meduase and never try to place there copies of the same complete (small) organism from successive images. Placing parts of rare and large objects permits to avoid overestimating them while it is less usefull for smaller organisms.
I checked in the UVP5 taxo guide... and cannot find the DUPLICATE category which explains why the category may be used in different ways ! This category should thus be renamed !!!!
On a very praticle point of view, I do not think that it is realisticly possible to obtain an efficient and reliable detection of the fact that two objects are the same.
